services:
  service:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: fechronizo
    container_name: fechronizoservice-container
    environment:
      - "DB_URL=postgres://postgres:novek@db:5432/fechronizo?sslmode=disable"
      - "PORT=8080"
    ports:
      - "8080:8080"
    depends_on:
      - db
      - migrate

  db:
    image: postgres:13-alpine
    container_name: fechronizodb-container
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: novek
      POSTGRES_DB: fechronizo
    volumes:
      - fechronizo-postgres-data:/var/lib/postgresql/data
  migrate:
    build:
      context: ..
      dockerfile: docker/Dockerfile.migrate
    image: fechronizomigrations
    container_name: fechronizomigrations-container
    command: ["./run_migrations.sh"]
    depends_on:
      - db
volumes:
  fechronizo-postgres-data: