services:
  service:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: rssagg
    container_name: rssaggservice-container
    environment:
      - "DB_URL=postgres://postgres:novek@db:5432/rssagg?sslmode=disable"
      - "PORT=8080"
    ports:
      - "8080:8080"
    depends_on:
      - db
      - migrate

  db:
    image: postgres:13-alpine
    container_name: rssaggdb-container
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: novek
      POSTGRES_DB: rssagg
    volumes:
      - rssagg-postgres-data:/var/lib/postgresql/data
  migrate:
    build:
      context: ..
      dockerfile: docker/Dockerfile.migrate
    image: rssaggmigrations
    container_name: rssaggmigrations-container
    command: ["./run_migrations.sh"]
    depends_on:
      - db
volumes:
  rssagg-postgres-data: